export const constants = {
     API_IP:"http://192.168.0.23:3300/",
     API_VERSION:"v1/auth",
     DOKTOR_DEGISTIR_AD:"DOKTOR.DEGISTIR_AD",
     DOKTOR_DEGISTIR_SOYAD:"DOKTOR.DEGISTIR_SOYAD",
     DOKTOR_EKLE:"DOKTOR.EKLE",
     HASTA_DEGISTIR_AD:"HASTA.DEGISTIR_AD",
     HASTA_DEGISTIR_SOYAD:"HASTA.DEGISTIR_SOYAD",
     HASTA_EKLE:"HASTA.EKLE",
     LOG_IN:"LOG_IN",
     LOG_OUT:"LOG_OUT",     
}